# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibra" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "91a1af2c1a9f491762ae4a4a6e0c50a0edbdcc23a4e649d5d1b1b21208ce0e29"
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
    end
    on_arm do
      sha256 "9048b753f9824e192a3f1a337a0eb8390dbf5388e7487d99a5e16d9408b5127e"
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a2604f7a8c28827ba737ec3d490b5699940f94c1c33afa2a51192fdbe51a52d"
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
    end
    on_arm do
      sha256 "835f22cc00daba33882573af87d10eed62ae1da1249fabb74d0d2a48265bcac4"
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
    end
  end

  name "dibra"
  desc "A minimal Ansible-like configuration management tool written in Go"
  homepage "https://github.com/Gjergj/dibra"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibra"]
    end
  end

  # No zap stanza required

end
