# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibra" do
  name "dibra"
  desc "A minimal Ansible-like configuration management tool written in Go"
  homepage "https://github.com/Gjergj/dibra"
  version "0.0.28"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibra"

  on_macos do
    on_intel do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
      sha256 "cfb8910bb9e3537150ca7560e27d4bd1dcde69bb91dbcc86a9a75173eeda6672"
    end
    on_arm do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
      sha256 "f5e254259b2abfdb120b3b78fa588d33ed47f8a538462d9e537787a5d6f984d5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
      sha256 "c8c1e15eec558a0fb72b07dde3e9e9f7ae3080f84dd03c0416ac18c40bc50cab"
    end
    on_arm do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
      sha256 "c6e6c44c8395bda37b345c7eaffa16cc6c542cc35c9ad3c86b4117e962958e22"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibra"]
    end
  end

  # No zap stanza required
end
