# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibra" do
  name "dibra"
  desc "A minimal Ansible-like configuration management tool written in Go"
  homepage "https://github.com/Gjergj/dibra"
  version "0.0.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibra"

  on_macos do
    on_intel do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
      sha256 "a8308ac6595741d8bf8d6252853de881de69881fe6ba6b7728b901a69cf47a45"
    end
    on_arm do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
      sha256 "38eb2c2b8831fa73cbf9ae60939ff87f72ece0e13a65923c58eaeb7e1512a96e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
      sha256 "c941a76c9920b4c478535e2da82248f9ae2141f71ac5b5490d4d21257534d85b"
    end
    on_arm do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Gjergj/dibra/"
      sha256 "6e4a2277512c0abed8a948998f59c89a5033b9e35c4cab47d8bd1b348bc2a271"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibra"]
    end
  end

  # No zap stanza required
end
