# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibra" do
  name "dibra"
  desc "A minimal Ansible-like configuration management tool written in Go"
  homepage "https://github.com/Gjergj/dibra"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibra"

  on_macos do
    on_intel do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_amd64.tar.gz"
      sha256 "402060b15a0013d6a4c635677d580ea9eb8674797069d429f754e23f37dfd9ae"
    end
    on_arm do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_arm64.tar.gz"
      sha256 "d09b700c2683ef34971a2dc1e2c3705d7c297ddf1ad02e65f7b3d4f4cca9a06e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_amd64.tar.gz"
      sha256 "14863ca028687730234e0c13610c68b67d961d423370ca9c0da52964a89d71e1"
    end
    on_arm do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_arm64.tar.gz"
      sha256 "d3f26e5373da7c7ca5a387ce32365d33044abb12c6ca5188a2f3c660cdf88ada"
    end
  end

  # No zap stanza required
end
