# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibra" do
  name "dibra"
  desc "A minimal Ansible-like configuration management tool written in Go"
  homepage "https://github.com/Gjergj/dibra"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibra"

  on_macos do
    on_intel do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_amd64.tar.gz"
      sha256 "66201cb976cb5a92fb0794a43e494f3dd167b65b5f022cf6f8efeb3fa139c880"
    end
    on_arm do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_darwin_arm64.tar.gz"
      sha256 "dc9485b425d5fb9f865279ceff85c9409d3d6082db9b6898e6624eb070531f83"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_amd64.tar.gz"
      sha256 "d1d2c3213fdd8144a92c5f3617d11791dde1796fa374460492afc1d46ce49fef"
    end
    on_arm do
      url "https://github.com/Gjergj/dibra/releases/download/v#{version}/dibra_#{version}_linux_arm64.tar.gz"
      sha256 "d7665651bf847a48f6291c196d63f39e60f9dd5c713656761db32fdb34d43f05"
    end
  end

  # No zap stanza required
end
